"""
Pydantic models for Qontinui action schema.

This module provides type-safe Python models equivalent to the TypeScript
action schema from qontinui-web. These models enable validation, parsing,
and type-safe access to action configurations.

All models are now organized in focused submodules under models/ for better
maintainability. This module re-exports everything for backward compatibility.
"""

# Re-export all models from the organized submodules
from .models import (
    ACTION_CONFIG_MAP,
    Action,
    BaseActionSettings,
    BreakActionConfig,
    ClickActionConfig,
    ConditionConfig,
    Connection,
    Connections,
    ContinueActionConfig,
    Coordinates,
    CoordinatesTarget,
    CurrentPositionTarget,
    DragActionConfig,
    ExecutionSettings,
    FilterActionConfig,
    FilterCondition,
    FindActionConfig,
    FindStateImageActionConfig,
    GetVariableActionConfig,
    GoToStateActionConfig,
    HighlightActionConfig,
    HotkeyActionConfig,
    IfActionConfig,
    ImageTarget,
    KeyDownActionConfig,
    KeyPressActionConfig,
    KeyUpActionConfig,
    LastFindResultTarget,
    LoggingOptions,
    LogLevel,
    LoopActionConfig,
    LoopCollection,
    MapActionConfig,
    MapTransform,
    MatchAdjustment,
    MathOperationActionConfig,
    MouseButton,
    MouseDownActionConfig,
    MouseMoveActionConfig,
    MouseUpActionConfig,
    PatternOptions,
    PollingConfig,
    ReduceActionConfig,
    Region,
    RegionTarget,
    RepetitionOptions,
    RunWorkflowActionConfig,
    ScreenshotActionConfig,
    ScreenshotSaveConfig,
    ScrollActionConfig,
    SearchOptions,
    SearchStrategy,
    SetVariableActionConfig,
    SortActionConfig,
    StateStringTarget,
    StringOperationActionConfig,
    StringOperationParameters,
    SwitchActionConfig,
    SwitchCase,
    TargetConfig,
    TextSearchOptions,
    TextSource,
    TextTarget,
    TryCatchActionConfig,
    TypeActionConfig,
    ValueSource,
    VanishActionConfig,
    Variables,
    VerificationConfig,
    VerificationMode,
    WaitActionConfig,
    WaitCondition,
    Workflow,
    WorkflowMetadata,
    WorkflowRepetition,
    WorkflowSettings,
    WorkflowVisibility,
    get_typed_config,
)

__all__ = [
    # Core action model
    "Action",
    "ACTION_CONFIG_MAP",
    "get_typed_config",
    # Base types
    "LogLevel",
    "MouseButton",
    "SearchStrategy",
    "VerificationMode",
    "WorkflowVisibility",
    # Geometry
    "Coordinates",
    "Region",
    # Logging
    "LoggingOptions",
    # Execution
    "BaseActionSettings",
    "ExecutionSettings",
    "RepetitionOptions",
    # Search
    "MatchAdjustment",
    "PatternOptions",
    "PollingConfig",
    "SearchOptions",
    "TextSearchOptions",
    # Targets
    "CoordinatesTarget",
    "CurrentPositionTarget",
    "ImageTarget",
    "LastFindResultTarget",
    "RegionTarget",
    "StateStringTarget",
    "TargetConfig",
    "TextTarget",
    # Verification
    "VerificationConfig",
    # Mouse actions
    "ClickActionConfig",
    "DragActionConfig",
    "HighlightActionConfig",
    "MouseDownActionConfig",
    "MouseMoveActionConfig",
    "MouseUpActionConfig",
    "ScrollActionConfig",
    # Keyboard actions
    "HotkeyActionConfig",
    "KeyDownActionConfig",
    "KeyPressActionConfig",
    "KeyUpActionConfig",
    "TextSource",
    "TypeActionConfig",
    # Find actions
    "FindActionConfig",
    "FindStateImageActionConfig",
    "VanishActionConfig",
    "WaitActionConfig",
    "WaitCondition",
    # Control flow
    "BreakActionConfig",
    "ConditionConfig",
    "ContinueActionConfig",
    "IfActionConfig",
    "LoopActionConfig",
    "LoopCollection",
    "SwitchActionConfig",
    "SwitchCase",
    "TryCatchActionConfig",
    # Data operations
    "FilterActionConfig",
    "FilterCondition",
    "GetVariableActionConfig",
    "MapActionConfig",
    "MapTransform",
    "MathOperationActionConfig",
    "ReduceActionConfig",
    "SetVariableActionConfig",
    "SortActionConfig",
    "StringOperationActionConfig",
    "StringOperationParameters",
    "ValueSource",
    # State actions
    "GoToStateActionConfig",
    "RunWorkflowActionConfig",
    "ScreenshotActionConfig",
    "ScreenshotSaveConfig",
    "WorkflowRepetition",
    # Workflow
    "Connection",
    "Connections",
    "Variables",
    "Workflow",
    "WorkflowMetadata",
    "WorkflowSettings",
]
