"""Cross-language fingerprint hash consistency tests.

Verifies that the Python FNV-1a hash implementation produces identical
hashes to the TypeScript implementation in element-fingerprint.ts.

These test vectors were generated by the TypeScript implementation.
If this test fails, the two implementations have diverged and recordings
will produce mismatched fingerprint hashes.
"""

import ctypes


def compute_hash_sync(
    structural_path: str,
    position_zone: str,
    role: str,
    accessible_name: str | None,
    size_category: str,
) -> str:
    """FNV-1a hash matching the TypeScript computeHashSync().

    Input format: "structuralPath|positionZone|role|accessibleName|sizeCategory"
    Output: 16-char hex string (two 32-bit FNV-1a hashes concatenated).
    """
    input_str = f"{structural_path}|{position_zone}|{role}|{accessible_name or ''}|{size_category}"

    h1 = 0x811C9DC5
    h2 = 0x811C9DC5

    for char in input_str:
        c = ord(char)
        # h1 ^= c; h1 = Math.imul(h1, 0x01000193)
        h1 ^= c
        h1 = ctypes.c_int32(h1 * 0x01000193).value
        # h2 ^= c * 31; h2 = Math.imul(h2, 0x01000193)
        h2 ^= ctypes.c_int32(c * 31).value
        h2 = ctypes.c_int32(h2 * 0x01000193).value

    # Convert to unsigned 32-bit and format as hex
    hex1 = format(ctypes.c_uint32(h1).value, "08x")
    hex2 = format(ctypes.c_uint32(h2).value, "08x")
    return hex1 + hex2


# Test vectors from TypeScript computeHashSync() — DO NOT MODIFY
# Format: (structuralPath, positionZone, role, accessibleName, sizeCategory, expectedHash)
TEST_VECTORS = [
    (
        "header > nav > button",
        "header",
        "button",
        "Menu",
        "button",
        "332bcf7901518bd9",
    ),  # Button in header
    (
        "main > form > div > input",
        "main",
        "textbox",
        "Email",
        "small",
        "314e89fb4502cc0b",
    ),  # Text input in main form
    (
        "div > div > dialog",
        "modal",
        "dialog",
        "Confirm Delete",
        "large",
        "a94df5a4c8e52c9a",
    ),  # Modal dialog
    (
        "aside > ul > li > a",
        "sidebar-left",
        "link",
        "Dashboard",
        "button",
        "8174509c620d7ab2",
    ),  # List item in sidebar
    (
        "footer > div > a",
        "footer",
        "link",
        "Privacy Policy",
        "button",
        "4873c371fbca621d",
    ),  # Footer link
    (
        "main > section > h1",
        "main",
        "heading",
        None,
        "medium",
        "e5444cd6ebe1bfac",
    ),  # Heading with no name
    (
        "main > form > select",
        "main",
        "combobox",
        "Country",
        "small",
        "6d8e56731c4558c7",
    ),  # Select in main
    ("main > div", "main", "", None, "panel", "198907dce9e35536"),  # Panel full width
    (
        "header > div > button",
        "header",
        "button",
        "Close",
        "icon",
        "87c26e378cea2acf",
    ),  # Icon button
    (
        "main > form > div > input",
        "main",
        "checkbox",
        "Remember me",
        "icon",
        "c2d6dff7e4d85f8f",
    ),  # Checkbox in form
]


class TestFingerprintHashConsistency:
    """Verify Python hash matches TypeScript hash for the same inputs."""

    def test_produces_16_char_hex(self) -> None:
        for sp, pz, r, an, sc, _ in TEST_VECTORS:
            result = compute_hash_sync(sp, pz, r, an, sc)
            assert len(result) == 16, f"Expected 16 chars, got {len(result)}: {result}"
            assert all(c in "0123456789abcdef" for c in result)

    def test_all_hashes_unique(self) -> None:
        hashes = {compute_hash_sync(sp, pz, r, an, sc) for sp, pz, r, an, sc, _ in TEST_VECTORS}
        assert len(hashes) == len(TEST_VECTORS)

    def test_deterministic(self) -> None:
        for sp, pz, r, an, sc, _ in TEST_VECTORS:
            h1 = compute_hash_sync(sp, pz, r, an, sc)
            h2 = compute_hash_sync(sp, pz, r, an, sc)
            assert h1 == h2

    def test_matches_typescript_vectors(self) -> None:
        """THE critical test — Python must produce the same hash as TypeScript."""
        for sp, pz, r, an, sc, expected in TEST_VECTORS:
            actual = compute_hash_sync(sp, pz, r, an, sc)
            assert actual == expected, (
                f"Hash mismatch for input '{sp}|{pz}|{r}|{an or ''}|{sc}':\n"
                f"  Python:     {actual}\n"
                f"  TypeScript: {expected}"
            )
