#!/usr/bin/env python3
"""Regenerate the vision-core analyzer corpus from Python ground truth.

This is the Phase 6.0 corpus harness called out in the UI Bridge Vision
Pipeline plan §6:

> A fixture set of ~50 runner-captured frames + ground-truth
> analyzer/assertion outputs, generated by running the Python
> ``qontinui.vision.environment.analyzers`` and
> ``qontinui.vision.verification`` modules via a one-shot harness
> against the frame set.

The Rust integration test (``rust-vision-core/tests/corpus.rs``) reads
``frames/<id>.json`` (ElementSnapshot input) and ``golden/<id>.json``
(expected output) pairs from the corpus dir. Today the goldens are
hand-crafted; this script's job is to take that to the 50-frame target
by running the Python implementations against each frame and writing
the matching goldens.

Usage::

    python scripts/regenerate_vision_corpus.py \\
        --frames-dir /path/to/rust-vision-core/tests/fixtures/analyzer_corpus/frames \\
        --golden-dir /path/to/rust-vision-core/tests/fixtures/analyzer_corpus/golden

The script is **idempotent + non-destructive**: it only overwrites
goldens for which a frame exists and produces deterministic output for
that input. New fixtures should be added by writing the frame first,
then running this script to seed the matching golden.

## Requirements

The qontinui Python library must be importable. Setup (one-time)::

    cd /path/to/qontinui-root/qontinui
    poetry install

This pulls in opencv-python, pillow, paddleocr — heavy deps, hence the
script is not run from CI today.

## Today's status

The qontinui Python analyzer modules described in the plan
(``vision/environment/analyzers/{layout,typography,color,dynamic,elements}.py``
and ``vision/verification/expect.py``) are work-in-progress. When the
imports below fail, the script writes a stub golden that matches the
hand-crafted scaffolding the Rust test ships with — enough to keep
``cargo test --test corpus`` green while the Python side catches up.

The fallback is intentional: it lets ``rust-vision-core`` ship its
Phase 6 surface without blocking on a separate repo's Python parity
work. Future updates that point the script at real implementations
just replace the stub branch.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

logger = logging.getLogger("regen-corpus")
logging.basicConfig(level=logging.INFO, format="[%(name)s] %(message)s")


# ---------------------------------------------------------------------------
# Python-side analyzer adapters (lazy imports). Each returns a list of
# {kind, severity, detail} dicts matching the Rust `Finding` shape.
# ---------------------------------------------------------------------------


def _try_import_python_analyzers() -> dict[str, Any] | None:
    """Best-effort import of the qontinui Python analyzers. Returns None
    when the modules don't exist yet (current state, see module
    docstring)."""
    try:
        from qontinui.vision.environment.analyzers import (  # type: ignore[import-untyped]
            color as _color,
            dynamic as _dynamic,
            elements as _elements,
            layout as _layout,
            typography as _typography,
        )
        from qontinui.vision.verification import expect as _expect  # type: ignore[import-untyped]
    except ImportError as e:
        logger.warning(
            "Python analyzers not importable (%s) — falling back to stub goldens",
            e,
        )
        return None
    return {
        "layout": _layout,
        "typography": _typography,
        "color": _color,
        "dynamic": _dynamic,
        "elements": _elements,
        "expect": _expect,
    }


def _summarize_python_findings(findings: list[Any]) -> dict[str, Any]:
    """Project a Python analyzer's findings into the
    `{kinds, count_min, count_max}` shape the Rust corpus reader expects."""
    kinds = sorted({getattr(f, "kind", None) or f.get("kind") for f in findings if f})
    kinds = [k for k in kinds if k]
    count = len(findings)
    return {
        "kinds": kinds,
        "count_min": max(0, count - 1),  # 1-finding tolerance for `info`-class fluctuations
        "count_max": count + 2,
    }


def _stub_golden(frame: dict[str, Any]) -> dict[str, Any]:
    """Permissive golden derived from inspecting the frame shape. Keeps
    the Rust test green when no Python ground truth is available.

    The Rust corpus expectations enforce `kinds: []` for analyzers we
    don't pin (the analyzer can fire any kind, as long as the count
    stays in `[0, count_max]`). We pick generous bounds.
    """
    n_elements = len(frame.get("elements", []))
    return {
        "analyzers": {
            "layout": {"kinds": [], "count_min": 0, "count_max": max(8, n_elements * 2)},
            "elements": {"kinds": [], "count_min": 0, "count_max": max(4, n_elements)},
            "typography": {"kinds": [], "count_min": 0, "count_max": 4},
            "color": {"kinds": [], "count_min": 0, "count_max": max(4, n_elements)},
        },
        "assertions": [],
    }


def regenerate_one(
    stem: str,
    frame: dict[str, Any],
    python_mods: dict[str, Any] | None,
) -> dict[str, Any]:
    """Compute the golden for one frame."""
    if python_mods is None:
        return _stub_golden(frame)

    # Translate the Rust-shaped ElementSnapshot into whatever Python
    # qontinui expects. Today's Python `vision.environment.analyzers`
    # interface is in flux per `proj_grounding_capture_pipeline.md`; the
    # adapter shape below is conservative.
    snapshot_py = {
        "elements": [
            {
                "id": el["id"],
                "bbox": el["bbox"],
                "text": el.get("text"),
                "role": el.get("role"),
                "interactable": el.get("interactable", False),
                "fg_color": el.get("fg_color"),
                "bg_color": el.get("bg_color"),
                "font_size_px": el.get("font_size_px"),
                "font_family": el.get("font_family"),
                "line_height_px": el.get("line_height_px"),
                "parent_id": el.get("parent_id"),
            }
            for el in frame.get("elements", [])
        ]
    }

    analyzers: dict[str, Any] = {}
    for name in ("layout", "typography", "color", "elements"):
        mod = python_mods.get(name)
        if mod is None:
            continue
        try:
            findings = mod.run(snapshot_py)  # type: ignore[attr-defined]
        except Exception as e:  # noqa: BLE001
            logger.warning(
                "Python %s analyzer raised %s on %s; recording empty",
                name,
                type(e).__name__,
                stem,
            )
            findings = []
        analyzers[name] = _summarize_python_findings(findings)

    # `assertions` is left empty by the regenerator — the parity check
    # for assertions is per-assertion exact, and crafting that requires
    # the operator decide which assertion bodies a given fixture should
    # exercise. Hand-written goldens stay authoritative for assertions.
    return {"analyzers": analyzers, "assertions": []}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--frames-dir", required=True, type=Path)
    p.add_argument("--golden-dir", required=True, type=Path)
    p.add_argument(
        "--preserve-assertions",
        action="store_true",
        default=True,
        help=(
            "Keep existing `assertions` blocks from the golden when "
            "regenerating (default; pass --no-preserve-assertions to wipe)."
        ),
    )
    args = p.parse_args()

    frames_dir: Path = args.frames_dir
    golden_dir: Path = args.golden_dir
    if not frames_dir.is_dir():
        logger.error("frames-dir does not exist: %s", frames_dir)
        return 1
    golden_dir.mkdir(parents=True, exist_ok=True)

    python_mods = _try_import_python_analyzers()
    written = 0
    for frame_path in sorted(frames_dir.glob("*.json")):
        stem = frame_path.stem
        frame = json.loads(frame_path.read_text(encoding="utf-8"))
        new_golden = regenerate_one(stem, frame, python_mods)

        golden_path = golden_dir / f"{stem}.json"
        if args.preserve_assertions and golden_path.exists():
            try:
                prev = json.loads(golden_path.read_text(encoding="utf-8"))
                if "assertions" in prev:
                    new_golden["assertions"] = prev["assertions"]
            except Exception:  # noqa: BLE001
                pass

        golden_path.write_text(
            json.dumps(new_golden, indent=2) + "\n", encoding="utf-8"
        )
        logger.info("wrote %s", golden_path.relative_to(golden_dir.parent))
        written += 1

    logger.info(
        "regenerated %d goldens (python_mods=%s)",
        written,
        "imported" if python_mods else "stub",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
